name: docker
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v3
    - 
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - 
      name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: 1.6.1
    - 
      name: Configure poetry
      shell: bash
      run: poetry config virtualenvs.create false
    - 
      name: View poetry version
      run: poetry --version
    - 
      name: Install dependencies
      run: poetry install
    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Prepare gaussian build
      run: . ./build.sh gaussian
    -
      name: Push gaussian tag
      uses: docker/build-push-action@v3
      with:
        context: builds/gaussian
        push: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/konan-titanic-model:${{ github.ref_name }}-gaussian
    - 
      name: Prepare knn build
      run: . ./build.sh knn
    -
      name: Push knn tag
      uses: docker/build-push-action@v3
      with:
        context: builds/knn
        push: true
        tags: |
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/konan-titanic-model:${{ github.ref_name }}-knn
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/konan-titanic-model:latest
