name: quality
on:
  push:
    branches:
    - "**"
    - "!main"
jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: 1.6.1
    - name: Configure poetry
      shell: bash
      run: poetry config virtualenvs.create false
    - name: View poetry version
      run: poetry --version
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with flake8
      run: |
        flake8
    # - name: Test with pytest
    #   run: |
    #     pytest -v tests
